#######################

###########differences total
lablevelptdiffhrtotal=noboilingpthrtotal-lablevelpthrtotal
verygoodptdiffhrtotal=noboilingpthrtotal-verygoodpthrtotal
moderateptdiffhrtotal=noboilingpthrtotal-moderatepthrtotal
goodptdiffhrtotal=noboilingpthrtotal-goodpthrtotal
loweffectiveptdiffhrtotal=noboilingpthrtotal-loweffectivepthrtotal
ineffectiveptdiffhrtotal=noboilingpthrtotal-ineffectivepthrtotal
negativeptdiffhrtotal=noboilingpthrtotal-negativepthrtotal

lablevelptdiffmrtotal=noboilingptmrtotal-lablevelptmrtotal
verygoodptdiffmrtotal=noboilingptmrtotal-verygoodptmrtotal
goodptdiffmrtotal=noboilingptmrtotal-goodptmrtotal
moderateptdiffmrtotal=noboilingptmrtotal-moderateptmrtotal
loweffectiveptdiffmrtotal=noboilingptmrtotal-loweffectiveptmrtotal
ineffectiveptdiffmrtotal=noboilingptmrtotal-ineffectiveptmrtotal
negativeptdiffmrtotal=noboilingptmrtotal-negativeptmrtotal

lablevelptdifflrtotal=noboilingptlrtotal-lablevelptlrtotal
verygoodptdifflrtotal=noboilingptlrtotal-verygoodptlrtotal
goodptdifflrtotal=noboilingptlrtotal-goodptlrtotal
moderateptdifflrtotal=noboilingptlrtotal-moderateptlrtotal
loweffectiveptdifflrtotal=noboilingptlrtotal-loweffectiveptlrtotal
ineffectiveptdifflrtotal=noboilingptlrtotal-ineffectiveptlrtotal
negativeptdifflrtotal=noboilingptlrtotal-negativeptlrtotal