lablevelptdiffhrchild=noboilingpthrchild-lablevelpthrchild
verygoodptdiffhrchild=noboilingpthrchild-verygoodpthrchild
moderateptdiffhrchild=noboilingpthrchild-moderatepthrchild
goodptdiffhrchild=noboilingpthrchild-goodpthrchild
loweffectiveptdiffhrchild=noboilingpthrchild-loweffectivepthrchild
ineffectiveptdiffhrchild=noboilingpthrchild-ineffectivepthrchild
negativeptdiffhrchild=noboilingpthrchild-negativepthrchild

lablevelptdiffmrchild=noboilingptmrchild-lablevelptmrchild
verygoodptdiffmrchild=noboilingptmrchild-verygoodptmrchild
goodptdiffmrchild=noboilingptmrchild-goodptmrchild
moderateptdiffmrchild=noboilingptmrchild-moderateptmrchild
loweffectiveptdiffmrchild=noboilingptmrchild-loweffectiveptmrchild
ineffectiveptdiffmrchild=noboilingptmrchild-ineffectiveptmrchild
negativeptdiffmrchild=noboilingptmrchild-negativeptmrchild

lablevelptdifflrchild=noboilingptlrchild-lablevelptlrchild
verygoodptdifflrchild=noboilingptlrchild-verygoodptlrchild
goodptdifflrchild=noboilingptlrchild-goodptlrchild
moderateptdifflrchild=noboilingptlrchild-moderateptlrchild
loweffectiveptdifflrchild=noboilingptlrchild-loweffectiveptlrchild
ineffectiveptdifflrchild=noboilingptlrchild-ineffectiveptlrchild
negativeptdifflrchild=noboilingptlrchild-negativeptlrchild

## USE these
#actual water values for adult
lablevelptdiffhr=noboilingpthr-lablevelpthr
verygoodptdiffhr=noboilingpthr-verygoodpthr
moderateptdiffhr=noboilingpthr-moderatepthr
goodptdiffhr=noboilingpthr-goodpthr
loweffectiveptdiffhr=noboilingpthr-loweffectivepthr
ineffectiveptdiffhr=noboilingpthr-ineffectivepthr
negativeptdiffhr=noboilingpthr-negativepthr



lablevelptdiffmr=noboilingptmr-lablevelptmr
verygoodptdiffmr=noboilingptmr-verygoodptmr
goodptdiffmr=noboilingptmr-goodptmr
moderateptdiffmr=noboilingptmr-moderateptmr
loweffectiveptdiffmr=noboilingptmr-loweffectiveptmr
ineffectiveptdiffmr=noboilingptmr-ineffectiveptmr
negativeptdiffmr=noboilingptmr-negativeptmr



lablevelptdifflr=noboilingptlr-lablevelptlr
verygoodptdifflr=noboilingptlr-verygoodptlr
goodptdifflr=noboilingptlr-goodptlr
moderateptdifflr=noboilingptlr-moderateptlr
loweffectiveptdifflr=noboilingptlr-loweffectiveptlr
ineffectiveptdifflr=noboilingptlr-ineffectiveptlr
negativeptdifflr=noboilingptlr-negativeptlr
