#########################################################################################################################
#read in values to create totals of differences

#watersummaryadultlow<-read.csv(file.path(currentresultspath,paste("waterDALYsdata",country,"adultlow.csv",sep="")),header=TRUE) #example
#watersummaryadultlowsd<-read.csv(file.path(currentresultspath,paste("waterDALYsdatasd",country,"adultlow.csv",sep="")),header=TRUE) #example  
print("negative boiling")
#negative boiling
waterDALYsnegativeboilingdiffadultlow<-read.csv(file.path(currentresultspath,paste("waterDALYsnegativeboilingdiff",country,"adultlow.csv",sep="")),header=TRUE)
waterDALYsnegativeboilingdiffadultmedium<-read.csv(file.path(currentresultspath,paste("waterDALYsnegativeboilingdiff",country,"adultmedium.csv",sep="")),header=TRUE)
waterDALYsnegativeboilingdiffadulthigh<-read.csv(file.path(currentresultspath,paste("waterDALYsnegativeboilingdiff",country,"adulthigh.csv",sep="")),header=TRUE)
waterDALYsnegativeboilingdiffchildlow<-read.csv(file.path(currentresultspath,paste("waterDALYsnegativeboilingdiff",country,"childlow.csv",sep="")),header=TRUE)
waterDALYsnegativeboilingdiffchildmedium<-read.csv(file.path(currentresultspath,paste("waterDALYsnegativeboilingdiff",country,"childmedium.csv",sep="")),header=TRUE)
waterDALYsnegativeboilingdiffchildhigh<-read.csv(file.path(currentresultspath,paste("waterDALYsnegativeboilingdiff",country,"childhigh.csv",sep="")),header=TRUE)
waterDALYsnegativeboilingvaluesadultlow<-read.csv(file.path(currentresultspath,paste("waterDALYsnegativeboilingvalues",country,"adultlow.csv",sep="")),header=TRUE)
waterDALYsnegativeboilingvaluesadultmedium<-read.csv(file.path(currentresultspath,paste("waterDALYsnegativeboilingvalues",country,"adultmedium.csv",sep="")),header=TRUE)
waterDALYsnegativeboilingvaluesadulthigh<-read.csv(file.path(currentresultspath,paste("waterDALYsnegativeboilingvalues",country,"adulthigh.csv",sep="")),header=TRUE)
waterDALYsnegativeboilingvalueschildlow<-read.csv(file.path(currentresultspath,paste("waterDALYsnegativeboilingvalues",country,"childlow.csv",sep="")),header=TRUE)
waterDALYsnegativeboilingvalueschildmedium<-read.csv(file.path(currentresultspath,paste("waterDALYsnegativeboilingvalues",country,"childmedium.csv",sep="")),header=TRUE)
waterDALYsnegativeboilingvalueschildhigh<-read.csv(file.path(currentresultspath,paste("waterDALYsnegativeboilingvalues",country,"childhigh.csv",sep="")),header=TRUE)
print("adding negative")
waterDALYsnegativeboilingvaluesTOTALlow=unlist(arrange(waterDALYsnegativeboilingvaluesadultlow)+arrange(waterDALYsnegativeboilingvaluesadultlow))
waterDALYsnegativeboilingvaluesTOTALmedium=unlist(arrange(waterDALYsnegativeboilingvaluesadultlow)+arrange(waterDALYsnegativeboilingvaluesadultmedium))
waterDALYsnegativeboilingvaluesTOTALhigh=unlist(arrange(waterDALYsnegativeboilingvaluesadultlow)+arrange(waterDALYsnegativeboilingvaluesadulthigh))
waterDALYsnegativeboilingdiffTOTALlow=unlist(arrange(waterDALYsnegativeboilingdiffadultlow)+arrange(waterDALYsnegativeboilingdiffadultlow))
waterDALYsnegativeboilingdiffTOTALmedium=unlist(arrange(waterDALYsnegativeboilingdiffadultlow)+arrange(waterDALYsnegativeboilingdiffadultmedium))
waterDALYsnegativeboilingdiffTOTALhigh=unlist(arrange(waterDALYsnegativeboilingdiffadultlow)+arrange(waterDALYsnegativeboilingdiffadulthigh))
print("mean")
negativeptlrtotal=mean(waterDALYsnegativeboilingdiffTOTALlow)
negativeptmrtotal=mean(waterDALYsnegativeboilingvaluesTOTALmedium)
negativepthrtotal=mean(waterDALYsnegativeboilingdiffTOTALhigh)
negativeptlrsdtotal=sd(waterDALYsnegativeboilingdiffTOTALlow)
print("sd")
negativeptmrsdtotal=sd(waterDALYsnegativeboilingvaluesTOTALmedium)
negativepthrsdtotal=sd(waterDALYsnegativeboilingdiffTOTALhigh)
negativeptdifflrtotal=mean(waterDALYsnegativeboilingdiffTOTALlow)
negativeptdiffmrtotal=mean(waterDALYsnegativeboilingdiffTOTALmedium)
negativeptdiffhrtotal=mean(waterDALYsnegativeboilingdiffTOTALhigh)
negativeptdifflrtotalsd=sd(waterDALYsnegativeboilingdiffTOTALlow)
negativeptdiffmrtotalsd=sd(waterDALYsnegativeboilingdiffTOTALmedium)
negativeptdiffhrtotalsd=sd(waterDALYsnegativeboilingdiffTOTALhigh)
#######################################################################
print("end negative boiling")
#lab boiling
waterDALYslabboilingdiffadultlow<-read.csv(file.path(currentresultspath,paste("waterDALYslabboilingdiff",country,"adultlow.csv",sep="")),header=TRUE)
waterDALYslabboilingdiffadultmedium<-read.csv(file.path(currentresultspath,paste("waterDALYslabboilingdiff",country,"adultmedium.csv",sep="")),header=TRUE)
waterDALYslabboilingdiffadulthigh<-read.csv(file.path(currentresultspath,paste("waterDALYslabboilingdiff",country,"adulthigh.csv",sep="")),header=TRUE)
waterDALYslabboilingdiffchildlow<-read.csv(file.path(currentresultspath,paste("waterDALYslabboilingdiff",country,"childlow.csv",sep="")),header=TRUE)
waterDALYslabboilingdiffchildmedium<-read.csv(file.path(currentresultspath,paste("waterDALYslabboilingdiff",country,"childmedium.csv",sep="")),header=TRUE)
waterDALYslabboilingdiffchildhigh<-read.csv(file.path(currentresultspath,paste("waterDALYslabboilingdiff",country,"childhigh.csv",sep="")),header=TRUE)
waterDALYslabboilingvaluesadultlow<-read.csv(file.path(currentresultspath,paste("waterDALYslabboilingvalues",country,"adultlow.csv",sep="")),header=TRUE)
waterDALYslabboilingvaluesadultmedium<-read.csv(file.path(currentresultspath,paste("waterDALYslabboilingvalues",country,"adultmedium.csv",sep="")),header=TRUE)
waterDALYslabboilingvaluesadulthigh<-read.csv(file.path(currentresultspath,paste("waterDALYslabboilingvalues",country,"adulthigh.csv",sep="")),header=TRUE)
waterDALYslabboilingvalueschildlow<-read.csv(file.path(currentresultspath,paste("waterDALYslabboilingvalues",country,"childlow.csv",sep="")),header=TRUE)
waterDALYslabboilingvalueschildmedium<-read.csv(file.path(currentresultspath,paste("waterDALYslabboilingvalues",country,"childmedium.csv",sep="")),header=TRUE)
waterDALYslabboilingvalueschildhigh<-read.csv(file.path(currentresultspath,paste("waterDALYslabboilingvalues",country,"childhigh.csv",sep="")),header=TRUE)
waterDALYslabboilingvaluesTOTALlow=unlist(arrange(waterDALYslabboilingvaluesadultlow)+arrange(waterDALYslabboilingvaluesadultlow))
waterDALYslabboilingvaluesTOTALmedium=unlist(arrange(waterDALYslabboilingvaluesadultlow)+arrange(waterDALYslabboilingvaluesadultmedium))
waterDALYslabboilingvaluesTOTALhigh=unlist(arrange(waterDALYslabboilingvaluesadultlow)+arrange(waterDALYslabboilingvaluesadulthigh))
waterDALYslabboilingdiffTOTALlow=unlist(arrange(waterDALYslabboilingdiffadultlow)+arrange(waterDALYslabboilingdiffadultlow))
waterDALYslabboilingdiffTOTALmedium=unlist(arrange(waterDALYslabboilingdiffadultlow)+arrange(waterDALYslabboilingdiffadultmedium))
waterDALYslabboilingdiffTOTALhigh=unlist(arrange(waterDALYslabboilingdiffadultlow)+arrange(waterDALYslabboilingdiffadulthigh))

lablevelptlrtotal=mean(waterDALYslabboilingdiffTOTALlow)
lablevelptmrtotal=mean(waterDALYslabboilingvaluesTOTALmedium)
lablevelpthrtotal=mean(waterDALYslabboilingdiffTOTALhigh)
lablevelptlrsdtotal=sd(waterDALYslabboilingdiffTOTALlow)
lablevelptmrsdtotal=sd(waterDALYslabboilingvaluesTOTALmedium)
lablevelpthrsdtotal=sd(waterDALYslabboilingdiffTOTALhigh)
lablevelptdifflrtotal=mean(waterDALYslabboilingdiffTOTALlow)
lablevelptdiffmrtotal=mean(waterDALYslabboilingdiffTOTALmedium)
lablevelptdiffhrtotal=mean(waterDALYslabboilingdiffTOTALhigh)
lablevelptdifflrtotalsd=sd(waterDALYslabboilingdiffTOTALlow)
lablevelptdiffmrtotalsd=sd(waterDALYslabboilingdiffTOTALmedium)
lablevelptdiffhrtotalsd=sd(waterDALYslabboilingdiffTOTALhigh)

########################################

#very good/good
waterDALYsgoodboilingdiffadultlow<-read.csv(file.path(currentresultspath,paste("waterDALYsgoodboilingdiff",country,"adultlow.csv",sep="")),header=TRUE)
waterDALYsgoodboilingdiffadultmedium<-read.csv(file.path(currentresultspath,paste("waterDALYsgoodboilingdiff",country,"adultmedium.csv",sep="")),header=TRUE)
waterDALYsgoodboilingdiffadulthigh<-read.csv(file.path(currentresultspath,paste("waterDALYsgoodboilingdiff",country,"adulthigh.csv",sep="")),header=TRUE)
waterDALYsgoodboilingdiffchildlow<-read.csv(file.path(currentresultspath,paste("waterDALYsgoodboilingdiff",country,"childlow.csv",sep="")),header=TRUE)
waterDALYsgoodboilingdiffchildmedium<-read.csv(file.path(currentresultspath,paste("waterDALYsgoodboilingdiff",country,"childmedium.csv",sep="")),header=TRUE)
waterDALYsgoodboilingdiffchildhigh<-read.csv(file.path(currentresultspath,paste("waterDALYsgoodboilingdiff",country,"childhigh.csv",sep="")),header=TRUE)
waterDALYsgoodboilingvaluesadultlow<-read.csv(file.path(currentresultspath,paste("waterDALYsgoodboilingvalues",country,"adultlow.csv",sep="")),header=TRUE)
waterDALYsgoodboilingvaluesadultmedium<-read.csv(file.path(currentresultspath,paste("waterDALYsgoodboilingvalues",country,"adultmedium.csv",sep="")),header=TRUE)
waterDALYsgoodboilingvaluesadulthigh<-read.csv(file.path(currentresultspath,paste("waterDALYsgoodboilingvalues",country,"adulthigh.csv",sep="")),header=TRUE)
waterDALYsgoodboilingvalueschildlow<-read.csv(file.path(currentresultspath,paste("waterDALYsgoodboilingvalues",country,"childlow.csv",sep="")),header=TRUE)
waterDALYsgoodboilingvalueschildmedium<-read.csv(file.path(currentresultspath,paste("waterDALYsgoodboilingvalues",country,"childmedium.csv",sep="")),header=TRUE)
waterDALYsgoodboilingvalueschildhigh<-read.csv(file.path(currentresultspath,paste("waterDALYsgoodboilingvalues",country,"childhigh.csv",sep="")),header=TRUE)
waterDALYsgoodboilingvaluesTOTALlow=unlist(arrange(waterDALYsgoodboilingvaluesadultlow)+arrange(waterDALYsgoodboilingvaluesadultlow))
waterDALYsgoodboilingvaluesTOTALmedium=unlist(arrange(waterDALYsgoodboilingvaluesadultlow)+arrange(waterDALYsgoodboilingvaluesadultmedium))
waterDALYsgoodboilingvaluesTOTALhigh=unlist(arrange(waterDALYsgoodboilingvaluesadultlow)+arrange(waterDALYsgoodboilingvaluesadulthigh))
waterDALYsgoodboilingdiffTOTALlow=unlist(arrange(waterDALYsgoodboilingdiffadultlow)+arrange(waterDALYsgoodboilingdiffadultlow))
waterDALYsgoodboilingdiffTOTALmedium=unlist(arrange(waterDALYsgoodboilingdiffadultlow)+arrange(waterDALYsgoodboilingdiffadultmedium))
waterDALYsgoodboilingdiffTOTALhigh=unlist(arrange(waterDALYsgoodboilingdiffadultlow)+arrange(waterDALYsgoodboilingdiffadulthigh))

verygoodptlrtotal=mean(waterDALYsgoodboilingdiffTOTALlow)
verygoodptmrtotal=mean(waterDALYsgoodboilingvaluesTOTALmedium)
verygoodpthrtotal=mean(waterDALYsgoodboilingdiffTOTALhigh)
verygoodptlrsdtotal=sd(waterDALYsgoodboilingdiffTOTALlow)
verygoodptmrsdtotal=sd(waterDALYsgoodboilingvaluesTOTALmedium)
verygoodpthrsdtotal=sd(waterDALYsgoodboilingdiffTOTALhigh)
verygoodptdifflrtotal=mean(waterDALYsgoodboilingdiffTOTALlow)
verygoodptdiffmrtotal=mean(waterDALYsgoodboilingdiffTOTALmedium)
verygoodptdiffhrtotal=mean(waterDALYsgoodboilingdiffTOTALhigh)
verygoodptdifflrtotalsd=sd(waterDALYsgoodboilingdiffTOTALlow)
verygoodptdiffmrtotalsd=sd(waterDALYsgoodboilingdiffTOTALmedium)
verygoodptdiffhrtotalsd=sd(waterDALYsgoodboilingdiffTOTALhigh)

########################################


########################################

#good/moderate
waterDALYsmoderateboilingdiffadultlow<-read.csv(file.path(currentresultspath,paste("waterDALYsmoderateboilingdiff",country,"adultlow.csv",sep="")),header=TRUE)
waterDALYsmoderateboilingdiffadultmedium<-read.csv(file.path(currentresultspath,paste("waterDALYsmoderateboilingdiff",country,"adultmedium.csv",sep="")),header=TRUE)
waterDALYsmoderateboilingdiffadulthigh<-read.csv(file.path(currentresultspath,paste("waterDALYsmoderateboilingdiff",country,"adulthigh.csv",sep="")),header=TRUE)
waterDALYsmoderateboilingdiffchildlow<-read.csv(file.path(currentresultspath,paste("waterDALYsmoderateboilingdiff",country,"childlow.csv",sep="")),header=TRUE)
waterDALYsmoderateboilingdiffchildmedium<-read.csv(file.path(currentresultspath,paste("waterDALYsmoderateboilingdiff",country,"childmedium.csv",sep="")),header=TRUE)
waterDALYsmoderateboilingdiffchildhigh<-read.csv(file.path(currentresultspath,paste("waterDALYsmoderateboilingdiff",country,"childhigh.csv",sep="")),header=TRUE)
waterDALYsmoderateboilingvaluesadultlow<-read.csv(file.path(currentresultspath,paste("waterDALYsmoderateboilingvalues",country,"adultlow.csv",sep="")),header=TRUE)
waterDALYsmoderateboilingvaluesadultmedium<-read.csv(file.path(currentresultspath,paste("waterDALYsmoderateboilingvalues",country,"adultmedium.csv",sep="")),header=TRUE)
waterDALYsmoderateboilingvaluesadulthigh<-read.csv(file.path(currentresultspath,paste("waterDALYsmoderateboilingvalues",country,"adulthigh.csv",sep="")),header=TRUE)
waterDALYsmoderateboilingvalueschildlow<-read.csv(file.path(currentresultspath,paste("waterDALYsmoderateboilingvalues",country,"childlow.csv",sep="")),header=TRUE)
waterDALYsmoderateboilingvalueschildmedium<-read.csv(file.path(currentresultspath,paste("waterDALYsmoderateboilingvalues",country,"childmedium.csv",sep="")),header=TRUE)
waterDALYsmoderateboilingvalueschildhigh<-read.csv(file.path(currentresultspath,paste("waterDALYsmoderateboilingvalues",country,"childhigh.csv",sep="")),header=TRUE)
waterDALYsmoderateboilingvaluesTOTALlow=unlist(arrange(waterDALYsmoderateboilingvaluesadultlow)+arrange(waterDALYsmoderateboilingvaluesadultlow))
waterDALYsmoderateboilingvaluesTOTALmedium=unlist(arrange(waterDALYsmoderateboilingvaluesadultlow)+arrange(waterDALYsmoderateboilingvaluesadultmedium))
waterDALYsmoderateboilingvaluesTOTALhigh=unlist(arrange(waterDALYsmoderateboilingvaluesadultlow)+arrange(waterDALYsmoderateboilingvaluesadulthigh))
waterDALYsmoderateboilingdiffTOTALlow=unlist(arrange(waterDALYsmoderateboilingdiffadultlow)+arrange(waterDALYsmoderateboilingdiffadultlow))
waterDALYsmoderateboilingdiffTOTALmedium=unlist(arrange(waterDALYsmoderateboilingdiffadultlow)+arrange(waterDALYsmoderateboilingdiffadultmedium))
waterDALYsmoderateboilingdiffTOTALhigh=unlist(arrange(waterDALYsmoderateboilingdiffadultlow)+arrange(waterDALYsmoderateboilingdiffadulthigh))

goodptlrtotal=mean(waterDALYsmoderateboilingdiffTOTALlow)
goodptmrtotal=mean(waterDALYsmoderateboilingvaluesTOTALmedium)
goodpthrtotal=mean(waterDALYsmoderateboilingdiffTOTALhigh)
goodptlrsdtotal=sd(waterDALYsmoderateboilingdiffTOTALlow)
goodptmrsdtotal=sd(waterDALYsmoderateboilingvaluesTOTALmedium)
goodpthrsdtotal=sd(waterDALYsmoderateboilingdiffTOTALhigh)
goodptdifflrtotal=mean(waterDALYsmoderateboilingdiffTOTALlow)
goodptdiffmrtotal=mean(waterDALYsmoderateboilingdiffTOTALmedium)
goodptdiffhrtotal=mean(waterDALYsmoderateboilingdiffTOTALhigh)
goodptdifflrtotalsd=sd(waterDALYsmoderateboilingdiffTOTALlow)
goodptdiffmrtotalsd=sd(waterDALYsmoderateboilingdiffTOTALmedium)
goodptdiffhrtotalsd=sd(waterDALYsmoderateboilingdiffTOTALhigh)

########################################

########################################

#moderate/ineffective boiling
waterDALYsineffectiveboilingdiffadultlow<-read.csv(file.path(currentresultspath,paste("ineffectiveboilingdiff",country,"adultlow.csv",sep="")),header=TRUE)
waterDALYsineffectiveboilingdiffadultmedium<-read.csv(file.path(currentresultspath,paste("ineffectiveboilingdiff",country,"adultmedium.csv",sep="")),header=TRUE)
waterDALYsineffectiveboilingdiffadulthigh<-read.csv(file.path(currentresultspath,paste("ineffectiveboilingdiff",country,"adulthigh.csv",sep="")),header=TRUE)
waterDALYsineffectiveboilingdiffchildlow<-read.csv(file.path(currentresultspath,paste("ineffectiveboilingdiff",country,"childlow.csv",sep="")),header=TRUE)
waterDALYsineffectiveboilingdiffchildmedium<-read.csv(file.path(currentresultspath,paste("ineffectiveboilingdiff",country,"childmedium.csv",sep="")),header=TRUE)
waterDALYsineffectiveboilingdiffchildhigh<-read.csv(file.path(currentresultspath,paste("ineffectiveboilingdiff",country,"childhigh.csv",sep="")),header=TRUE)
waterDALYsineffectiveboilingvaluesadultlow<-read.csv(file.path(currentresultspath,paste("ineffectiveboilingvalues",country,"adultlow.csv",sep="")),header=TRUE)
waterDALYsineffectiveboilingvaluesadultmedium<-read.csv(file.path(currentresultspath,paste("ineffectiveboilingvalues",country,"adultmedium.csv",sep="")),header=TRUE)
waterDALYsineffectiveboilingvaluesadulthigh<-read.csv(file.path(currentresultspath,paste("ineffectiveboilingvalues",country,"adulthigh.csv",sep="")),header=TRUE)
waterDALYsineffectiveboilingvalueschildlow<-read.csv(file.path(currentresultspath,paste("ineffectiveboilingvalues",country,"childlow.csv",sep="")),header=TRUE)
waterDALYsineffectiveboilingvalueschildmedium<-read.csv(file.path(currentresultspath,paste("ineffectiveboilingvalues",country,"childmedium.csv",sep="")),header=TRUE)
waterDALYsineffectiveboilingvalueschildhigh<-read.csv(file.path(currentresultspath,paste("ineffectiveboilingvalues",country,"childhigh.csv",sep="")),header=TRUE)
waterDALYsineffectiveboilingvaluesTOTALlow=unlist(arrange(waterDALYsineffectiveboilingvaluesadultlow)+arrange(waterDALYsineffectiveboilingvaluesadultlow))
waterDALYsineffectiveboilingvaluesTOTALmedium=unlist(arrange(waterDALYsineffectiveboilingvaluesadultlow)+arrange(waterDALYsineffectiveboilingvaluesadultmedium))
waterDALYsineffectiveboilingvaluesTOTALhigh=unlist(arrange(waterDALYsineffectiveboilingvaluesadultlow)+arrange(waterDALYsineffectiveboilingvaluesadulthigh))
waterDALYsineffectiveboilingdiffTOTALlow=unlist(arrange(waterDALYsineffectiveboilingdiffadultlow)+arrange(waterDALYsineffectiveboilingdiffadultlow))
waterDALYsineffectiveboilingdiffTOTALmedium=unlist(arrange(waterDALYsineffectiveboilingdiffadultlow)+arrange(waterDALYsineffectiveboilingdiffadultmedium))
waterDALYsineffectiveboilingdiffTOTALhigh=unlist(arrange(waterDALYsineffectiveboilingdiffadultlow)+arrange(waterDALYsineffectiveboilingdiffadulthigh))

moderateptlrtotal=mean(waterDALYsineffectiveboilingdiffTOTALlow)
moderateptmrtotal=mean(waterDALYsineffectiveboilingvaluesTOTALmedium)
moderatepthrtotal=mean(waterDALYsineffectiveboilingdiffTOTALhigh)
moderateptlrsdtotal=sd(waterDALYsineffectiveboilingdiffTOTALlow)
moderateptmrsdtotal=sd(waterDALYsineffectiveboilingvaluesTOTALmedium)
moderatepthrsdtotal=sd(waterDALYsineffectiveboilingdiffTOTALhigh)
moderateptdifflrtotal=mean(waterDALYsineffectiveboilingdiffTOTALlow)
moderateptdiffmrtotal=mean(waterDALYsineffectiveboilingdiffTOTALmedium)
moderateptdiffhrtotal=mean(waterDALYsineffectiveboilingdiffTOTALhigh)
moderateptdifflrtotalsd=sd(waterDALYsineffectiveboilingdiffTOTALlow)
moderateptdiffmrtotalsd=sd(waterDALYsineffectiveboilingdiffTOTALmedium)
moderateptdiffhrtotalsd=sd(waterDALYsineffectiveboilingdiffTOTALhigh)

########################################

#loweffective/worse
waterDALYsworseboilingdiffadultlow<-read.csv(file.path(currentresultspath,paste("waterDALYsworseboilingdiff",country,"adultlow.csv",sep="")),header=TRUE)
waterDALYsworseboilingdiffadultmedium<-read.csv(file.path(currentresultspath,paste("waterDALYsworseboilingdiff",country,"adultmedium.csv",sep="")),header=TRUE)
waterDALYsworseboilingdiffadulthigh<-read.csv(file.path(currentresultspath,paste("waterDALYsworseboilingdiff",country,"adulthigh.csv",sep="")),header=TRUE)
waterDALYsworseboilingdiffchildlow<-read.csv(file.path(currentresultspath,paste("waterDALYsworseboilingdiff",country,"childlow.csv",sep="")),header=TRUE)
waterDALYsworseboilingdiffchildmedium<-read.csv(file.path(currentresultspath,paste("waterDALYsworseboilingdiff",country,"childmedium.csv",sep="")),header=TRUE)
waterDALYsworseboilingdiffchildhigh<-read.csv(file.path(currentresultspath,paste("waterDALYsworseboilingdiff",country,"childhigh.csv",sep="")),header=TRUE)
waterDALYsworseboilingvaluesadultlow<-read.csv(file.path(currentresultspath,paste("waterDALYsworseboilingvalues",country,"adultlow.csv",sep="")),header=TRUE)
waterDALYsworseboilingvaluesadultmedium<-read.csv(file.path(currentresultspath,paste("waterDALYsworseboilingvalues",country,"adultmedium.csv",sep="")),header=TRUE)
waterDALYsworseboilingvaluesadulthigh<-read.csv(file.path(currentresultspath,paste("waterDALYsworseboilingvalues",country,"adulthigh.csv",sep="")),header=TRUE)
waterDALYsworseboilingvalueschildlow<-read.csv(file.path(currentresultspath,paste("waterDALYsworseboilingvalues",country,"childlow.csv",sep="")),header=TRUE)
waterDALYsworseboilingvalueschildmedium<-read.csv(file.path(currentresultspath,paste("waterDALYsworseboilingvalues",country,"childmedium.csv",sep="")),header=TRUE)
waterDALYsworseboilingvalueschildhigh<-read.csv(file.path(currentresultspath,paste("waterDALYsworseboilingvalues",country,"childhigh.csv",sep="")),header=TRUE)
waterDALYsworseboilingvaluesTOTALlow=unlist(arrange(waterDALYsworseboilingvaluesadultlow)+arrange(waterDALYsworseboilingvaluesadultlow))
waterDALYsworseboilingvaluesTOTALmedium=unlist(arrange(waterDALYsworseboilingvaluesadultlow)+arrange(waterDALYsworseboilingvaluesadultmedium))
waterDALYsworseboilingvaluesTOTALhigh=unlist(arrange(waterDALYsworseboilingvaluesadultlow)+arrange(waterDALYsworseboilingvaluesadulthigh))
waterDALYsworseboilingdiffTOTALlow=unlist(arrange(waterDALYsworseboilingdiffadultlow)+arrange(waterDALYsworseboilingdiffadultlow))
waterDALYsworseboilingdiffTOTALmedium=unlist(arrange(waterDALYsworseboilingdiffadultlow)+arrange(waterDALYsworseboilingdiffadultmedium))
waterDALYsworseboilingdiffTOTALhigh=unlist(arrange(waterDALYsworseboilingdiffadultlow)+arrange(waterDALYsworseboilingdiffadulthigh))

loweffectiveptlrtotal=mean(waterDALYsworseboilingdiffTOTALlow)
loweffectiveptmrtotal=mean(waterDALYsworseboilingvaluesTOTALmedium)
loweffectivepthrtotal=mean(waterDALYsworseboilingdiffTOTALhigh)
loweffectiveptlrsdtotal=sd(waterDALYsworseboilingdiffTOTALlow)
loweffectiveptmrsdtotal=sd(waterDALYsworseboilingvaluesTOTALmedium)
loweffectivepthrsdtotal=sd(waterDALYsworseboilingdiffTOTALhigh)
loweffectiveptdifflrtotal=mean(waterDALYsworseboilingdiffTOTALlow)
loweffectiveptdiffmrtotal=mean(waterDALYsworseboilingdiffTOTALmedium)
loweffectiveptdiffhrtotal=mean(waterDALYsworseboilingdiffTOTALhigh)
loweffectiveptdifflrtotalsd=sd(waterDALYsworseboilingdiffTOTALlow)
loweffectiveptdiffmrtotalsd=sd(waterDALYsworseboilingdiffTOTALmedium)
loweffectiveptdiffhrtotalsd=sd(waterDALYsworseboilingdiffTOTALhigh)

########################################

########################################

#ineffective/badzero
waterDALYsbadzeroboilingdiffadultlow<-read.csv(file.path(currentresultspath,paste("waterDALYsbadzeroboilingdiff",country,"adultlow.csv",sep="")),header=TRUE)
waterDALYsbadzeroboilingdiffadultmedium<-read.csv(file.path(currentresultspath,paste("waterDALYsbadzeroboilingdiff",country,"adultmedium.csv",sep="")),header=TRUE)
waterDALYsbadzeroboilingdiffadulthigh<-read.csv(file.path(currentresultspath,paste("waterDALYsbadzeroboilingdiff",country,"adulthigh.csv",sep="")),header=TRUE)
waterDALYsbadzeroboilingdiffchildlow<-read.csv(file.path(currentresultspath,paste("waterDALYsbadzeroboilingdiff",country,"childlow.csv",sep="")),header=TRUE)
waterDALYsbadzeroboilingdiffchildmedium<-read.csv(file.path(currentresultspath,paste("waterDALYsbadzeroboilingdiff",country,"childmedium.csv",sep="")),header=TRUE)
waterDALYsbadzeroboilingdiffchildhigh<-read.csv(file.path(currentresultspath,paste("waterDALYsbadzeroboilingdiff",country,"childhigh.csv",sep="")),header=TRUE)
waterDALYsbadzeroboilingvaluesadultlow<-read.csv(file.path(currentresultspath,paste("waterDALYsbadzeroboilingvalues",country,"adultlow.csv",sep="")),header=TRUE)
waterDALYsbadzeroboilingvaluesadultmedium<-read.csv(file.path(currentresultspath,paste("waterDALYsbadzeroboilingvalues",country,"adultmedium.csv",sep="")),header=TRUE)
waterDALYsbadzeroboilingvaluesadulthigh<-read.csv(file.path(currentresultspath,paste("waterDALYsbadzeroboilingvalues",country,"adulthigh.csv",sep="")),header=TRUE)
waterDALYsbadzeroboilingvalueschildlow<-read.csv(file.path(currentresultspath,paste("waterDALYsbadzeroboilingvalues",country,"childlow.csv",sep="")),header=TRUE)
waterDALYsbadzeroboilingvalueschildmedium<-read.csv(file.path(currentresultspath,paste("waterDALYsbadzeroboilingvalues",country,"childmedium.csv",sep="")),header=TRUE)
waterDALYsbadzeroboilingvalueschildhigh<-read.csv(file.path(currentresultspath,paste("waterDALYsbadzeroboilingvalues",country,"childhigh.csv",sep="")),header=TRUE)
waterDALYsbadzeroboilingvaluesTOTALlow=unlist(arrange(waterDALYsbadzeroboilingvaluesadultlow)+arrange(waterDALYsbadzeroboilingvaluesadultlow))
waterDALYsbadzeroboilingvaluesTOTALmedium=unlist(arrange(waterDALYsbadzeroboilingvaluesadultlow)+arrange(waterDALYsbadzeroboilingvaluesadultmedium))
waterDALYsbadzeroboilingvaluesTOTALhigh=unlist(arrange(waterDALYsbadzeroboilingvaluesadultlow)+arrange(waterDALYsbadzeroboilingvaluesadulthigh))
waterDALYsbadzeroboilingdiffTOTALlow=unlist(arrange(waterDALYsbadzeroboilingdiffadultlow)+arrange(waterDALYsbadzeroboilingdiffadultlow))
waterDALYsbadzeroboilingdiffTOTALmedium=unlist(arrange(waterDALYsbadzeroboilingdiffadultlow)+arrange(waterDALYsbadzeroboilingdiffadultmedium))
waterDALYsbadzeroboilingdiffTOTALhigh=unlist(arrange(waterDALYsbadzeroboilingdiffadultlow)+arrange(waterDALYsbadzeroboilingdiffadulthigh))

ineffectiveptlrtotal=mean(waterDALYsbadzeroboilingdiffTOTALlow)
ineffectiveptmrtotal=mean(waterDALYsbadzeroboilingvaluesTOTALmedium)
ineffectivepthrtotal=mean(waterDALYsbadzeroboilingdiffTOTALhigh)
ineffectiveptlrsdtotal=sd(waterDALYsbadzeroboilingdiffTOTALlow)
ineffectiveptmrsdtotal=sd(waterDALYsbadzeroboilingvaluesTOTALmedium)
ineffectivepthrsdtotal=sd(waterDALYsbadzeroboilingdiffTOTALhigh)
ineffectiveptdifflrtotal=mean(waterDALYsbadzeroboilingdiffTOTALlow)
ineffectiveptdiffmrtotal=mean(waterDALYsbadzeroboilingdiffTOTALmedium)
ineffectiveptdiffhrtotal=mean(waterDALYsbadzeroboilingdiffTOTALhigh)
ineffectiveptdifflrtotalsd=sd(waterDALYsbadzeroboilingdiffTOTALlow)
ineffectiveptdiffmrtotalsd=sd(waterDALYsbadzeroboilingdiffTOTALmedium)
ineffectiveptdiffhrtotalsd=sd(waterDALYsbadzeroboilingdiffTOTALhigh)

########################################

#ineffective/badzero
waterDALYsnoboilingdiffadultlow<-read.csv(file.path(currentresultspath,paste("waterDALYsnoboilingdiff",country,"adultlow.csv",sep="")),header=TRUE)
waterDALYsnoboilingdiffadultmedium<-read.csv(file.path(currentresultspath,paste("waterDALYsnoboilingdiff",country,"adultmedium.csv",sep="")),header=TRUE)
waterDALYsnoboilingdiffadulthigh<-read.csv(file.path(currentresultspath,paste("waterDALYsnoboilingdiff",country,"adulthigh.csv",sep="")),header=TRUE)
waterDALYsnoboilingdiffchildlow<-read.csv(file.path(currentresultspath,paste("waterDALYsnoboilingdiff",country,"childlow.csv",sep="")),header=TRUE)
waterDALYsnoboilingdiffchildmedium<-read.csv(file.path(currentresultspath,paste("waterDALYsnoboilingdiff",country,"childmedium.csv",sep="")),header=TRUE)
waterDALYsnoboilingdiffchildhigh<-read.csv(file.path(currentresultspath,paste("waterDALYsnoboilingdiff",country,"childhigh.csv",sep="")),header=TRUE)
waterDALYsnoboilingvaluesadultlow<-read.csv(file.path(currentresultspath,paste("waterDALYsnoboilingvalues",country,"adultlow.csv",sep="")),header=TRUE)
waterDALYsnoboilingvaluesadultmedium<-read.csv(file.path(currentresultspath,paste("waterDALYsnoboilingvalues",country,"adultmedium.csv",sep="")),header=TRUE)
waterDALYsnoboilingvaluesadulthigh<-read.csv(file.path(currentresultspath,paste("waterDALYsnoboilingvalues",country,"adulthigh.csv",sep="")),header=TRUE)
waterDALYsnoboilingvalueschildlow<-read.csv(file.path(currentresultspath,paste("waterDALYsnoboilingvalues",country,"childlow.csv",sep="")),header=TRUE)
waterDALYsnoboilingvalueschildmedium<-read.csv(file.path(currentresultspath,paste("waterDALYsnoboilingvalues",country,"childmedium.csv",sep="")),header=TRUE)
waterDALYsnoboilingvalueschildhigh<-read.csv(file.path(currentresultspath,paste("waterDALYsnoboilingvalues",country,"childhigh.csv",sep="")),header=TRUE)
waterDALYsnoboilingvaluesTOTALlow=unlist(arrange(waterDALYsnoboilingvaluesadultlow)+arrange(waterDALYsnoboilingvaluesadultlow))
waterDALYsnoboilingvaluesTOTALmedium=unlist(arrange(waterDALYsnoboilingvaluesadultlow)+arrange(waterDALYsnoboilingvaluesadultmedium))
waterDALYsnoboilingvaluesTOTALhigh=unlist(arrange(waterDALYsnoboilingvaluesadultlow)+arrange(waterDALYsnoboilingvaluesadulthigh))
waterDALYsnoboilingdiffTOTALlow=unlist(arrange(waterDALYsnoboilingdiffadultlow)+arrange(waterDALYsnoboilingdiffadultlow))
waterDALYsnoboilingdiffTOTALmedium=unlist(arrange(waterDALYsnoboilingdiffadultlow)+arrange(waterDALYsnoboilingdiffadultmedium))
waterDALYsnoboilingdiffTOTALhigh=unlist(arrange(waterDALYsnoboilingdiffadultlow)+arrange(waterDALYsnoboilingdiffadulthigh))

noboilingptlrtotal=mean(waterDALYsnoboilingdiffTOTALlow)
noboilingptmrtotal=mean(waterDALYsnoboilingvaluesTOTALmedium)
noboilingpthrtotal=mean(waterDALYsnoboilingdiffTOTALhigh)
noboilingptlrsdtotal=sd(waterDALYsnoboilingdiffTOTALlow)
noboilingptmrsdtotal=sd(waterDALYsnoboilingvaluesTOTALmedium)
noboilingpthrsdtotal=sd(waterDALYsnoboilingdiffTOTALhigh)
noboilingptdifflrtotal=mean(waterDALYsnoboilingdiffTOTALlow)
noboilingptdiffmrtotal=mean(waterDALYsnoboilingdiffTOTALmedium)
noboilingptdiffhrtotal=mean(waterDALYsnoboilingdiffTOTALhigh)
noboilingptdifflrtotalsd=sd(waterDALYsnoboilingdiffTOTALlow)
noboilingptdiffmrtotalsd=sd(waterDALYsnoboilingdiffTOTALmedium)
noboilingptdiffhrtotalsd=sd(waterDALYsnoboilingdiffTOTALhigh)

########################################

